language: python
services:
  - docker
before_install:
  - docker-compose up -d
install:
  - pip install -U setuptools
  - pip install poetry
  - poetry install
  - pip install codacy-coverage
after_success:
  - coverage xml
  - CODACY_PROJECT_TOKEN=6094c750148a4305b986d049385bbf9a python-codacy-coverage -r coverage.xml
jobs:
  include:
    - stage: test
      name: "Unit Tests"
      python:
        - "3.6.5"
        - "3.7-dev"
      script: make unit
    - stage: "Functional"
      name: "Functional Tests"
      python:
        - "3.7-dev"
      script: make deps-func func
