---
language: python
services:
  - docker
install:
  - pip install -U setuptools
  - pip install poetry
  - poetry install
  - pip install codacy-coverage
jobs:
  include:
    - stage: test
      before_install:
        - docker-compose up -d
      python:
        - "3.6.5"
        - "3.7-dev"
      after_success:
        - coverage xml
        - CODACY_PROJECT_TOKEN=6094c750148a4305b986d049385bbf9a python-codacy-coverage -r coverage.xml
    - stage: "Functional"
      python: "3.7-dev"
      name: "Functional Tests"
      before_install:
        - rm -rf /tmp/fastlane-tests
        - mkdir -p /tmp/fastlane-tests/{mongo,redis}
        - docker-compose --project-name fastlane-tests -f ./docker-compose-func-tests.yml up -d
      script: make func
script:
  - make unit
