language: python
python:
  - "3.6.5"
  - "3.7-dev"
services:
  - docker
before_install:
  - docker-compose up -d
install:
  - pip install -U setuptools
  - pip install poetry
  - poetry install
  - pip install codacy-coverage
jobs:
  include:
    - stage: test
      after_success:
        - coverage xml
        - CODACY_PROJECT_TOKEN=6094c750148a4305b986d049385bbf9a python-codacy-coverage -r coverage.xml
    - stage: "Functional"
      python: "3.7-dev"
      name: "Functional Tests"
      script: make deps-func func
script:
  - make unit
