version: '2'

services:
  mongo:
    image: mongo
    ports:
      - "27355:27017"
    volumes:
      - /tmp/fastlane-tests/mongo:/data/db
  redis:
    image: redis
    volumes:
      - /tmp/fastlane-tests/redis:/data
  docker-host:
    image: docker:stable-dind
    privileged: true
  fastlane:
    image: heynemann/fastlane:1.3.2
    ports:
      - "10000:10000"
    env_file:
      - docker-compose-func-tests.env
    depends_on:
      - mongo
      - redis
      - docker-host
